### ISSUE TITLE
Mirador failing when resource `@type` is "http://purl.org/dc/dcmitype/Image instead" of "dctypes:Image"

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador#1447]
While most manifests includes the shorthand “dctypes:Image” for the `@type` of their image resource, I believe it should be equally valid to have “http://purl.org/dc/dcmitype/Image” as the property of `@type`. 

New version of Mirador (perhaps >=2.5) are now resulting in an error in manifests that have "http://purl.org/dc/dcmitype/Image" instead of "dctypes:Image"

The console logs the following error:

Uncaught Error: Cannot create an image from type http://purl.org/dc/dcmitype/Image
    at ImageResourceFactory (http://projectmirador.org/demo/mirador.min.js:83:7101)
    at http://projectmirador.org/demo/mirador.min.js:83:465
    at Array.forEach (native)
    at CanvasObject (http://projectmirador.org/demo/mirador.min.js:83:422)
    at http://projectmirador.org/demo/mirador.min.js:88:28896
    at Array.reduce (native)
    at $.Window.buildCanvasesIndex (http://projectmirador.org/demo/mirador.min.js:88:27761)
    at $.Window.init (http://projectmirador.org/demo/mirador.min.js:88:24263)
    at $.Window (http://projectmirador.org/demo/mirador.min.js:88:23580)
    at $.Workspace.addWindow (http://projectmirador.org/demo/mirador.min.js:84:6605)

**Comment by jeffreycwitt** [comment]
@azaroth42 says the expanded form is not exactly valid IIIF, so I guess this isn't really a bug.
