### ISSUE TITLE
Mirador/SOLR issue DocValuesField "data" is too large,&#8203; must be <= 32766

### ISSUE THREAD

**Issue by dmnk1220** [ProjectMirador/mirador#1518]
We have installed at the Vatican Library an instance of Mirador  for use by curators providing annotations.
It means we have set up an annotation server that serves as a persistent annotation store for the team throughout a granted project that aims to provide annotations in Medieval manuscripts.
Due to some issues arisen we were forced to stop the creation of annotations in Mirador  (and our project timeline is now affected by this).

We have tried to analyse the stack consisting of Mirador, Simple Annotations Server and SOLR even if we are not developers and we are able to report the nature of the issues as well as to provide an example for each.
The data shown below are for a single entry, but of course we can provide other cases of the same issue type if needed.

The field "data" in the schema.xml is a string type, so it's very strange that a simple annotation like below generated an overflow (must be <= 32766) of that field.

Shelfmark/Folio:
Barb.lat.154 / f. 20v

Date and time:
08/02/2018 13:06:00

Shape:
White Square

Text:
Iniziale maggiore S di Suave Mari dorata inserita in una cornice quadrangolare che racchiude un paesaggio abitato da un satiro con corna lunate e zampe caprine che sorregge la lettera.

Issue:
After saving the annotation, the annotation disappeared

SOLR log:
8/2/2018 , 13:06:24
ERROR true 
RequestHandlerBase
org.apache.solr.common.SolrException:
Exception writing document id http://mirador.bav.local:8080/simpleAnnotationStore/annotation/1518091584197 to the index; possible analysis error: DocValuesField "data" is too large,&#8203; must be <= 32766

org.apache.solr.common.SolrException: Exception writing document id http://mirador.bav.local:8080/simpleAnnotationStore/annotation/1518091584197 to the index; possible analysis error: DocValuesField "data" is too large, must be <= 32766
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:199)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
	at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:98)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:180)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readIterator(JavaBinUpdateRequestCodec.java:136)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:306)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readNamedList(JavaBinUpdateRequestCodec.java:122)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:271)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:173)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:187)
	at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:108)
	at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:55)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: DocValuesField "data" is too large, must be <= 32766
	at org.apache.lucene.index.SortedDocValuesWriter.addValue(SortedDocValuesWriter.java:71)
	at org.apache.lucene.index.DefaultIndexingChain.indexDocValue(DefaultIndexingChain.java:567)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:483)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:403)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1571)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:924)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
	... 53 more

**Comment by mejackreed** [comment]
Closing this issue, as I think it was a Solr configuration problem with SimpleAnnotationServer.
