### ISSUE TITLE
Mirador/SOLR issue multiple values encountered for non multiValued field target

### ISSUE THREAD

**Issue by dmnk1220** [ProjectMirador/mirador#1519]
We have installed at the Vatican Library an instance of Mirador  for use by curators providing annotations.
It means we have set up an annotation server that serves as a persistent annotation store for the team throughout a granted project that aims to provide annotations in Medieval manuscripts.
Due to some issues arisen we were forced to stop the creation of annotations in Mirador  (and our project timeline is now affected by this).

We have tried to analyse the stack consisting of Mirador, Simple Annotations Server and SOLR even if we are not developers and we are able to report the nature of the issues as well as to provide an example for each.
The data shown below are for a single entry, but of course we can provide other cases of the same issue type if needed.

This type of issue is often also linked to the issue described in the link [https://github.com/ProjectMirador/mirador/issues/1517](https://github.com/ProjectMirador/mirador/issues/1517)

Shelfmark/Folio:
Vat.lat.5763 / f. 46r

Date and time:
09/02/2018 8:45

Shape:
2 Yellow squares

Text:
Così nel codice; si legga post quae nemo 		

Issue:
After saving annotations, I close or press <Ctrl + R> and annotations disappear.

SOLR log:
9/2/2018 , 08:45:17
ERROR false
RequestHandlerBase
org.apache.solr.common.SolrException: 
ERROR: [doc=http://mirador.bav.local:8080/simpleAnnotationStore/annotation/1518162317615] multiple values encountered for non multiValued field target:
[https://digi.vatlib.it/iiif/MSS_Vat.lat.5763/canvas/p0183,&#8203; https://digi.vatlib.it/iiif/MSS_Vat.lat.5763/canvas/p0183]

org.apache.solr.common.SolrException: ERROR: [doc=http://mirador.bav.local:8080/simpleAnnotationStore/annotation/1518162317615] multiple values encountered for non multiValued field target: [https://digi.vatlib.it/iiif/MSS_Vat.lat.5763/canvas/p0183, https://digi.vatlib.it/iiif/MSS_Vat.lat.5763/canvas/p0183]
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:150)
	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:922)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
	at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:98)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:180)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readIterator(JavaBinUpdateRequestCodec.java:136)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:306)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readNamedList(JavaBinUpdateRequestCodec.java:122)
	at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:271)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:251)
	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:173)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:187)
	at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:108)
	at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:55)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jbaiter** [comment]
I've run into this as well (with Elucidate as the annotation server, which is more forgiving in this regard), sometimes Mirador will create an annotation that targets two canvases instead of the single one the user made the annotation on.

**Comment by jbaiter** [comment]
Sadly no, I haven't really look further into the problem, since it does not directly break our workflow and we simply ignore the second target.
