### ISSUE TITLE
Error after 'npm start'

### ISSUE THREAD

**Issue by elymatos** [ProjectMirador/mirador#2599]
Hi,
I just cloned Mirador and I'm following the instructions at README.
It seems install was ok (no error at npm install) but after 'npm start' I receive (msg below). Some directions on that?
Thanks!
```

    ERROR in ./src/components/ManifestListItem.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'has' of undefined
        at resolvePath (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)

        at importModule (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
        at memoized (E:\devel\mirador\node_modules\lodash\memoize.js:62:23)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:203:62
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:193:30
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:181:28
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at PluginPass.Program (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:170:26)
        at newFn (E:\devel\mirador\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:88:12)
        at TraversalContext.visitQueue (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:118:16)
        at TraversalContext.visitSingle (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:90:19)
        at TraversalContext.visit (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:146:19)
        at Function.traverse.node (E:\devel\mirador\node_modules\@babel\traverse\lib\index.js:94:17)

        at traverse (E:\devel\mirador\node_modules\@babel\traverse\lib\index.js:76:12)
        at transformFile (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:88:29)
        at runSync (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:45:3)
        at runAsync (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:35:14)
        at process.nextTick (E:\devel\mirador\node_modules\@babel\core\lib\transform.js:34:34)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/containers/ManifestListItem.js 1:453-514 9:578-594
     @ ./src/components/WorkspaceAdd.js
     @ ./src/containers/WorkspaceAdd.js
     @ ./src/components/WorkspaceArea.js
     @ ./src/containers/WorkspaceArea.js
     @ ./src/components/App.js
     @ ./src/containers/App.js
     @ ./src/lib/MiradorViewer.js
     @ ./src/init.js
     @ ./src/index.js

    ERROR in ./src/components/AttributionPanel.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'has' of undefined
        at resolvePath (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)

        at importModule (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
        at memoized (E:\devel\mirador\node_modules\lodash\memoize.js:62:23)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:203:62
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:193:30
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:181:28
        at arrayEach (E:\devel\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (E:\devel\mirador\node_modules\lodash\forEach.js:38:10)
        at PluginPass.Program (E:\devel\mirador\node_modules\babel-plugin-lodash\lib\index.js:170:26)
        at newFn (E:\devel\mirador\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (E:\devel\mirador\node_modules\@babel\traverse\lib\path\context.js:88:12)
        at TraversalContext.visitQueue (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:118:16)
        at TraversalContext.visitSingle (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:90:19)
        at TraversalContext.visit (E:\devel\mirador\node_modules\@babel\traverse\lib\context.js:146:19)
        at Function.traverse.node (E:\devel\mirador\node_modules\@babel\traverse\lib\index.js:94:17)

        at traverse (E:\devel\mirador\node_modules\@babel\traverse\lib\index.js:76:12)
        at transformFile (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:88:29)
        at runSync (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:45:3)
        at runAsync (E:\devel\mirador\node_modules\@babel\core\lib\transformation\index.js:35:14)
        at process.nextTick (E:\devel\mirador\node_modules\@babel\core\lib\transform.js:34:34)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/containers/AttributionPanel.js 1:278-339 9:463-479
     @ ./src/components/CompanionWindowFactory.js
     @ ./src/containers/CompanionWindowFactory.js
     @ ./src/components/CompanionArea.js
     @ ./src/containers/CompanionArea.js
     @ ./src/components/Window.js
     @ ./src/containers/Window.js
     @ ./src/components/Workspace.js
     @ ./src/containers/Workspace.js
     @ ./src/components/WorkspaceArea.js
     @ ./src/containers/WorkspaceArea.js
     @ ./src/components/App.js
     @ ./src/containers/App.js
     @ ./src/lib/MiradorViewer.js
     @ ./src/init.js
     @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mirador@3.0.0-alpha.6 build:dev: `webpack --mode=development`
npm ERR! Exit status 2
npm ERR!
```

**Comment by Sebi11** [comment]
Same issue for me...

**Comment by mejackreed** [comment]
It seems like this might be related to an upstream issue in babel-plugin-lodash https://github.com/lodash/babel-plugin-lodash/issues/124

Could you please try and `npm prune` and then `npm start` to see if that works?

**Comment by Sebi11** [comment]
I try to clean my node_modules folder and run the commands above, but nothing changed. Thank you for the link to the other bug, I will follow it.

**Comment by mejackreed** [comment]
Hi is this still an issue with your development environment? I'm going to close the issue, but please reopen if you are still having issues.

**Comment by dobradovic** [comment]
I have same issue, any help?

**Comment by mejackreed** [comment]
What version of node and npm are you using?

**Comment by dobradovic** [comment]
npm - 6.14.8 
node v12.20.0

I cant figure out this for days... Any help and advice would be nice :)

**Comment by dobradovic** [comment]
this is error, maybe this could help you to see wider picture.

Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/nebojsa/Desktop/Chiara+(1)-1.3.0LastUpdated/assets/js/theme/global/quick-search.js: Cannot read property 'has' of undefined
    at resolvePath (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/babel-plugin-lodash/lib/importModule.js:22:24)
    at importModule (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/babel-plugin-lodash/lib/importModule.js:36:53)
    at memoized (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/lodash/memoize.js:62:23)
    at /Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/babel-plugin-lodash/lib/index.js:217:63
    at arrayEach (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/lodash/forEach.js:38:10)
    at /Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/babel-plugin-lodash/lib/index.js:193:30
    at arrayEach (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/lodash/forEach.js:38:10)
    at /Users/nebojsa/Desktop/Chiara+(:3009/1)-1.3.0LastUpdated/node_modules/babel-plugin-lodash/lib/index.js:181:28
    at Object../assets/js/theme/global/quick-search.js (theme-bundle.main.js:20290)
    at __webpack_require__ (bootstrap:63)
    at Module.<anonymous> (theme-bundle.main.js:19003)
    at Module../assets/js/theme/global.js (theme-bundle.main.js:19288)
    at __webpack_require__ (bootstrap:63)
    at Module.<anonymous> (bootstrap:196)
    at Module../assets/js/app.js (theme-bundle.main.js:985)
    at __webpack_require__ (bootstrap:63)
    at bootstrap:196
    at bootstrap:196

@mejackreed

**Comment by mejackreed** [comment]
Thanks for that.. I wonder if it has to do with the file path.

`Chiara+(1)-1.3.0LastUpdated` could you please modify the path to remove the `+`, `.`, and `()` characters?

**Comment by mejackreed** [comment]
Looking at this comment https://github.com/lodash/babel-plugin-lodash/issues/124#issuecomment-599450158 maybe there needs to be a more `[a-z]` similar path?

**Comment by dobradovic** [comment]
Man you saved me! It is working, finally! Thank you very much I really appreciate it, I was fixing this for 2 days... :) 👍 

@mejackreed
