### ISSUE TITLE
Issue with NPM Start

### ISSUE THREAD

**Issue by GroovinChip** [ProjectMirador/mirador#2758]
Hello,

I have cloned Mirador 3 and have done `npm install` and `npm start`. I get an error that others have experienced. I have reviewed all those other issues and tried the solutions there to no effect. Here is the stack trace:

```
C:\Users\ReubenT\Mirador 3\mirador>npm start

> mirador@3.0.0-alpha.12 start C:\Users\ReubenT\Mirador 3\mirador
> npm run build:dev && concurrently "npm run build:watch" "npm run server -- -p 4444"


> mirador@3.0.0-alpha.12 build:dev C:\Users\ReubenT\Mirador 3\mirador
> webpack --mode=development

Hash: fdb086dd2942426623e18059386da7764727c082
Version: webpack 4.34.0
Child
    Hash: fdb086dd2942426623e1
    Time: 3485ms
    Built at: 06/19/2019 3:48:10 PM
            Asset      Size  Chunks             Chunk Names
    m3core.umd.js  2.64 MiB    main  [emitted]  main
    Entrypoint main = m3core.umd.js
    [./src/index-core.js] 131 bytes {main} [built]
    [./src/state/actions/annotation.js] 2.68 KiB {main} [built]
    [./src/state/actions/auth.js] 3 KiB {main} [built]
    [./src/state/actions/canvas.js] 522 bytes {main} [built]
    [./src/state/actions/companionWindow.js] 1.44 KiB {main} [built]
    [./src/state/actions/config.js] 990 bytes {main} [built]
    [./src/state/actions/elasticLayout.js] 195 bytes {main} [built]
    [./src/state/actions/errors.js] 374 bytes {main} [built]
    [./src/state/actions/index.js] 360 bytes {main} [built]
    [./src/state/actions/infoResponse.js] 2.61 KiB {main} [built]
    [./src/state/actions/manifest.js] 1.94 KiB {main} [built]
    [./src/state/actions/search.js] 2.86 KiB {main} [built]
    [./src/state/actions/window.js] 4.45 KiB {main} [built]
    [./src/state/actions/workspace.js] 1.98 KiB {main} [built]
    [./src/state/createStore.js] 485 bytes {main} [built]
        + 280 hidden modules
Child
    Hash: 8059386da7764727c082
    Time: 5273ms
    Built at: 06/19/2019 3:48:11 PM
             Asset      Size  Chunks             Chunk Names
    mirador.min.js  16.4 MiB    main  [emitted]  main
    Entrypoint main = mirador.min.js
    [./src/index.js] 224 bytes {main} [built]
    [./src/init.js] 169 bytes {main} [built]
    [./src/lib/MiradorViewer.js] 2.15 KiB {main} [built]
    [./src/state/actions/annotation.js] 2.68 KiB {main} [built]
    [./src/state/actions/auth.js] 3 KiB {main} [built]
    [./src/state/actions/canvas.js] 522 bytes {main} [built]
    [./src/state/actions/companionWindow.js] 1.44 KiB {main} [built]
    [./src/state/actions/config.js] 990 bytes {main} [built]
    [./src/state/actions/elasticLayout.js] 195 bytes {main} [built]
    [./src/state/actions/errors.js] 374 bytes {main} [built]
    [./src/state/actions/index.js] 360 bytes {main} [built]
    [./src/state/actions/infoResponse.js] 2.61 KiB {main} [built]
    [./src/state/actions/manifest.js] 1.94 KiB {main} [built]
    [./src/state/reducers/index.js] 327 bytes {main} [built]
    [./src/state/selectors/index.js] 202 bytes {main} [built]
        + 1264 hidden modules

    ERROR in ./src/components/ManifestListItem.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'has' of undefined
        at resolvePath (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)
        at importModule (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
        at memoized (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\memoize.js:62:23)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:203:62
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:193:30
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:181:28
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at PluginPass.Program (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:170:26)
        at newFn (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:88:12)
        at TraversalContext.visitQueue (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:118:16)
        at TraversalContext.visitSingle (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:90:19)
        at TraversalContext.visit (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:146:19)
        at Function.traverse.node (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\index.js:94:17)
        at traverse (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\index.js:76:12)
        at transformFile (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:88:29)
        at runSync (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:45:3)
        at runAsync (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:35:14)
        at process.nextTick (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transform.js:34:34)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/containers/ManifestListItem.js 1:453-514 9:578-594
     @ ./src/components/WorkspaceAdd.js
     @ ./src/containers/WorkspaceAdd.js
     @ ./src/components/WorkspaceArea.js
     @ ./src/containers/WorkspaceArea.js
     @ ./src/components/App.js
     @ ./src/containers/App.js
     @ ./src/lib/MiradorViewer.js
     @ ./src/init.js
     @ ./src/index.js

    ERROR in ./src/components/AttributionPanel.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'has' of undefined
        at resolvePath (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)
        at importModule (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
        at memoized (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\memoize.js:62:23)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:203:62
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:193:30
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:181:28
        at arrayEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\ReubenT\Mirador 3\mirador\node_modules\lodash\forEach.js:38:10)
        at PluginPass.Program (C:\Users\ReubenT\Mirador 3\mirador\node_modules\babel-plugin-lodash\lib\index.js:170:26)
        at newFn (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\path\context.js:88:12)
        at TraversalContext.visitQueue (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:118:16)
        at TraversalContext.visitSingle (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:90:19)
        at TraversalContext.visit (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\context.js:146:19)
        at Function.traverse.node (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\index.js:94:17)
        at traverse (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\traverse\lib\index.js:76:12)
        at transformFile (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:88:29)
        at runSync (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:45:3)
        at runAsync (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transformation\index.js:35:14)
        at process.nextTick (C:\Users\ReubenT\Mirador 3\mirador\node_modules\@babel\core\lib\transform.js:34:34)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/containers/AttributionPanel.js 1:278-339 9:451-467
     @ ./src/components/CompanionWindowFactory.js
     @ ./src/containers/CompanionWindowFactory.js
     @ ./src/components/CompanionArea.js
     @ ./src/containers/CompanionArea.js
     @ ./src/components/Window.js
     @ ./src/containers/Window.js
     @ ./src/components/Workspace.js
     @ ./src/containers/Workspace.js
     @ ./src/components/WorkspaceArea.js
     @ ./src/containers/WorkspaceArea.js
     @ ./src/components/App.js
     @ ./src/containers/App.js
     @ ./src/lib/MiradorViewer.js
     @ ./src/init.js
     @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mirador@3.0.0-alpha.12 build:dev: `webpack --mode=development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mirador@3.0.0-alpha.12 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ReubenT\AppData\Roaming\npm-cache\_logs\2019-06-19T19_48_11_955Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mirador@3.0.0-alpha.12 start: `npm run build:dev && concurrently "npm run build:watch" "npm run server -- -p 4444"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mirador@3.0.0-alpha.12 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ReubenT\AppData\Roaming\npm-cache\_logs\2019-06-19T19_48_11_981Z-debug.log
```
Any help with this would be greatly appreciated.

**Comment by GroovinChip** [comment]
Closed due to https://github.com/ProjectMirador/mirador/pull/2769
