### ISSUE TITLE
Autocomplete dropdown on click searches for typed term not suggested term

### ISSUE THREAD

**Issue by AndrewZWood** [ProjectMirador/mirador#3208]
Version: "mirador": "3.0.0-beta.10"
Hello! I noticed while setting up my autocomplete service for my instance of Mirador that when I click on a suggested term Mirador sends off a request for the typed term and NOT the clicked on suggest term.
<img width="1833" alt="Screen Shot 2020-07-09 at 2 12 08 PM" src="https://user-images.githubusercontent.com/31103571/87078632-f41cdc80-c1f2-11ea-86f3-67c8a67e7a3f.png">

In this image's example Mirador sent off a request for `pos` but I clicked on `possible`.

I noticed there's an RC out as well so I gave that a try: ( "mirador": "3.0.0-rc.3" ):
When I tried the same interaction as stated above against `3.0.0-rc.3` I received the following error:

> TypeError: Cannot read property ‘annotations’ of undefined
    at Function.mapToProps (http://localhost:18080/assets/images/mirador.min.js:2:636409)
    at r (http://localhost:18080/assets/images/mirador.min.js:2:19759)
    at Function.r.mapToProps (http://localhost:18080/assets/images/mirador.min.js:2:19895)
    at r (http://localhost:18080/assets/images/mirador.min.js:2:19759)
    at http://localhost:18080/assets/images/mirador.min.js:2:21124
    at http://localhost:18080/assets/images/mirador.min.js:2:18547
    at Object.useMemo (http://localhost:18080/assets/images/mirador.min.js:2:1344097)
    at t.useMemo (http://localhost:18080/assets/images/mirador.min.js:2:1281106)
    at S (http://localhost:18080/assets/images/mirador.min.js:2:18491)
    at Ki (http://localhost:18080/assets/images/mirador.min.js:2:1339245)

The associated "CompanionWindow":
[miradorErrorCompanionWindow.txt](https://github.com/ProjectMirador/mirador/files/4898941/miradorErrorCompanionWindow.txt)

And for reference here's the output for my search and autocomplete service:
Search:
Request: http://localhost:8080/server/iiif/search/286a853d-3cf9-4a94-8044-d41dbbebe508?q=possible
Output: 
[IIIFSearchOutput.txt](https://github.com/ProjectMirador/mirador/files/4898961/IIIFSearchOutput.txt)

Suggest:
Request: http://localhost:8080/server/iiif/search/suggest/286a853d-3cf9-4a94-8044-d41dbbebe508?q=pos
Output: 
[IIIFSuggestOutput.txt](https://github.com/ProjectMirador/mirador/files/4898964/IIIFSuggestOutput.txt)

Thanks for reading.

**Comment by cbeer** [comment]
We made some major changes to the autocomplete widget after beta.10, and I'm not able to replicate this with our latest release candidate. Could you try with one of our newer releases (like rc.3) and verify this has since been fixed? Feel free to reopen this issue if it's still a problem.

**Comment by AndrewZWood** [comment]
@cbeer I also tested with rc3 like I stated in the initial post... I even provided the error I was given testing the issue and provided the related output.

**Comment by cbeer** [comment]
Ok. Since your endpoints are private, can you also give it a try with:

http://mirador-dev.netlify.app 

and 

https://deploy-preview-3211--mirador-dev.netlify.app

and let us know how it goes?

**Comment by AndrewZWood** [comment]
@cbeer 
The issue does not exist when I load my manifest against: [https://deploy-preview-3211--mirador-dev.netlify.app](https://deploy-preview-3211--mirador-dev.netlify.app) . Which is awesome!

But I experience a similar error like the one I originally reported when loading my manifest against: http://mirador-dev.netlify.app

Error output:
TypeError: Cannot read property 'annotations' of undefined
    at Function.mapToProps (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:653082)
    at r (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:19508)
    at Function.r.mapToProps (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:19644)
    at r (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:19508)
    at https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:20873
    at https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:18296
    at Object.useMemo (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:1285119)
    at t.useMemo (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:1222128)
    at S (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:18240)
    at Ki (https://mirador-dev.netlify.app/dist/mirador.min.js?v=1594412693936:2:1280267)

Companion window:
[compainionWindow.txt](https://github.com/ProjectMirador/mirador/files/4905233/compainionWindow.txt)

**Comment by cbeer** [comment]
Excellent. #3211 had my best guess at the problem. I'll mark that ready to go and we'll get it into the next release.
