### ISSUE TITLE
Fix or suppress OSD test warnings

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3746]
```
 console.error
   No TileSource was able to open undefined {
     crossOriginPolicy: false,
     ajaxWithCredentials: false,
     useCanvas: true
   }

   at console.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
   at Function.Object.<anonymous>.$.TileSource.determineType (node_modules/openseadragon/src/tilesource.js:978:15)
   at node_modules/openseadragon/src/viewer.js:2525:48

 console.error
   No TileSource was able to open undefined {
     crossOriginPolicy: false,
     ajaxWithCredentials: false,
     useCanvas: true
   }

   at console.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
   at Function.Object.<anonymous>.$.TileSource.determineType (node_modules/openseadragon/src/tilesource.js:978:15)
   at node_modules/openseadragon/src/viewer.js:2525:48

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewer.addSimpleImage] options.url is required

   at Object.<anonymous>.$.Viewer.addSimpleImage (node_modules/openseadragon/src/viewer.js:1626:19)
       at Array.map (<anonymous>)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewer.addSimpleImage] options.url is required

   at Object.<anonymous>.$.Viewer.addSimpleImage (node_modules/openseadragon/src/viewer.js:1626:19)
       at Array.map (<anonymous>)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewer.addSimpleImage] options.url is required

   at Object.<anonymous>.$.Viewer.addSimpleImage (node_modules/openseadragon/src/viewer.js:1626:19)
       at Array.map (<anonymous>)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewer.addSimpleImage] options.url is required

   at Object.<anonymous>.$.Viewer.addSimpleImage (node_modules/openseadragon/src/viewer.js:1626:19)
       at Array.map (<anonymous>)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.width must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:204:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.height must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:205:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.width must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:204:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.height must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:205:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.width must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:204:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.height must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:205:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.width must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:204:19)

 console.assert
   AssertionError [ERR_ASSERTION]: [Viewport._setContentBounds] bounds.height must be greater than 0

   at Object.<anonymous>.$.Viewport._setContentBounds (node_modules/openseadragon/src/viewport.js:205:19)
```

**Comment by marlo-longley** [comment]
Closing as stale -- new versions of OSD, and Jest >> Vite migration.
